name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checks-out
        uses: actions/checkout@v2
      # The hosted images have been updated with the latest of each LTS from v8, v10, v12, and v14.
      - name: Change Node version
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Test
        run: echo 'Skip test'
      - name: Generate
        run: |
          npm install
          npx hexo clean
          npx hexo generate
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./public
          git init
          git config user.name kimseongrim
          git config user.email kimseongrim@qq.com
          git remote add origin https://c02c0551aca805ef061b0dbf89108ba4179fec9a@github.com/kimseongrim/kimseongrim.github.io.git
          git checkout --orphan master
          git add --all
          git commit --allow-empty -m 'Deploying blog'
          git push origin master --force
          echo 'Deployment succesful!'
